name: E2E Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

jobs:
  cypress:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        suite: [web, api]
        browser: [chrome]

    env:
      # Essas envs chegam no Cypress como Cypress.env("FRONT_URL") / ("API_URL")
      CYPRESS_FRONT_URL: ${{ secrets.FRONT_URL }}
      CYPRESS_API_URL: ${{ secrets.API_URL }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm' # requer package-lock.json no repo

      - name: Install deps
        run: npm ci

      - name: Run Cypress (${{ matrix.suite }})
        uses: cypress-io/github-action@v6
        with:
          install: false
          browser: ${{ matrix.browser }}
          command: npm run test:${{ matrix.suite }} # <-- sem if/fi

      - name: Upload screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots-${{ matrix.suite }}
          path: cypress/screenshots
          if-no-files-found: ignore

      - name: Upload videos
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: videos-${{ matrix.suite }}
          path: cypress/videos
          if-no-files-found: ignore
